POST http://localhost:3000/register
content-type: application/json

{
  "firstName": "testName",
  "lastName": "testLastName",
  "email": "test@gmail.com",
  "pw": "testingPW123"
}

###

POST http://localhost:3000/login
content-type: application/json

{
  "email": "test@gmail.com",
  "pw": "testingPW123"
}

###
